/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthAuroraRouteImport } from "./routes/_auth/aurora"
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects/index"
import { Route as AuthAccountsIndexRouteImport } from "./routes/_auth/accounts/index"
import { Route as AuthProjectsProjectIdRouteImport } from "./routes/_auth/projects/$projectId"
import { Route as AuthProjectsProjectIdIndexRouteImport } from "./routes/_auth/projects/$projectId/index"
import { Route as AuthProjectsProjectIdNetworkRouteImport } from "./routes/_auth/projects/$projectId/network"
import { Route as AuthProjectsProjectIdStorageIndexRouteImport } from "./routes/_auth/projects/$projectId/storage/index"
import { Route as AuthProjectsProjectIdServicesIndexRouteImport } from "./routes/_auth/projects/$projectId/services/index"
import { Route as AuthProjectsProjectIdNetworkIndexRouteImport } from "./routes/_auth/projects/$projectId/network/index"
import { Route as AuthProjectsProjectIdComputeIndexRouteImport } from "./routes/_auth/projects/$projectId/compute/index"
import { Route as AuthProjectsProjectIdComputeImagesRouteImport } from "./routes/_auth/projects/$projectId/compute/images"
import { Route as AuthProjectsProjectIdComputeFlavorsRouteImport } from "./routes/_auth/projects/$projectId/compute/flavors"
import { Route as AuthProjectsProjectIdServicesPcaIndexRouteImport } from "./routes/_auth/projects/$projectId/services/pca/index"
import { Route as AuthProjectsProjectIdNetworkSecuritygroupsIndexRouteImport } from "./routes/_auth/projects/$projectId/network/securitygroups/index"
import { Route as AuthProjectsProjectIdNetworkFloatingipsIndexRouteImport } from "./routes/_auth/projects/$projectId/network/floatingips/index"
import { Route as AuthProjectsProjectIdComputeImagesIndexRouteImport } from "./routes/_auth/projects/$projectId/compute/images/index"
import { Route as AuthProjectsProjectIdComputeFlavorsIndexRouteImport } from "./routes/_auth/projects/$projectId/compute/flavors/index"
import { Route as AuthProjectsProjectIdComputeImagesImageIdRouteImport } from "./routes/_auth/projects/$projectId/compute/images/$imageId"
import { Route as AuthProjectsProjectIdComputeFlavorsFlavorIdRouteImport } from "./routes/_auth/projects/$projectId/compute/flavors/$flavorId"
import { Route as AuthProjectsProjectIdStorageProviderStorageTypeIndexRouteImport } from "./routes/_auth/projects/$projectId/storage/$provider/$storageType/index"
import { Route as AuthProjectsProjectIdServicesPcaPcaIdIndexRouteImport } from "./routes/_auth/projects/$projectId/services/pca/$pcaId/index"
import { Route as AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRouteImport } from "./routes/_auth/projects/$projectId/network/securitygroups/$securityGroupId/index"
import { Route as AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRouteImport } from "./routes/_auth/projects/$projectId/network/floatingips/$floatingIpId/index"
import { Route as AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRouteImport } from "./routes/_auth/projects/$projectId/services/pca/$pcaId/$certificateId"
import { Route as AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRouteImport } from "./routes/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
import { Route as AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRouteImport } from "./routes/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/objects/index"

const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuroraRoute = AuthAuroraRouteImport.update({
  id: "/aurora",
  path: "/aurora",
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsIndexRoute = AuthAccountsIndexRouteImport.update({
  id: "/accounts/",
  path: "/accounts/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdIndexRoute =
  AuthProjectsProjectIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdNetworkRoute =
  AuthProjectsProjectIdNetworkRouteImport.update({
    id: "/network",
    path: "/network",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdStorageIndexRoute =
  AuthProjectsProjectIdStorageIndexRouteImport.update({
    id: "/storage/",
    path: "/storage/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdServicesIndexRoute =
  AuthProjectsProjectIdServicesIndexRouteImport.update({
    id: "/services/",
    path: "/services/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdNetworkIndexRoute =
  AuthProjectsProjectIdNetworkIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthProjectsProjectIdNetworkRoute,
  } as any)
const AuthProjectsProjectIdComputeIndexRoute =
  AuthProjectsProjectIdComputeIndexRouteImport.update({
    id: "/compute/",
    path: "/compute/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdComputeImagesRoute =
  AuthProjectsProjectIdComputeImagesRouteImport.update({
    id: "/compute/images",
    path: "/compute/images",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdComputeFlavorsRoute =
  AuthProjectsProjectIdComputeFlavorsRouteImport.update({
    id: "/compute/flavors",
    path: "/compute/flavors",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdServicesPcaIndexRoute =
  AuthProjectsProjectIdServicesPcaIndexRouteImport.update({
    id: "/services/pca/",
    path: "/services/pca/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute =
  AuthProjectsProjectIdNetworkSecuritygroupsIndexRouteImport.update({
    id: "/securitygroups/",
    path: "/securitygroups/",
    getParentRoute: () => AuthProjectsProjectIdNetworkRoute,
  } as any)
const AuthProjectsProjectIdNetworkFloatingipsIndexRoute =
  AuthProjectsProjectIdNetworkFloatingipsIndexRouteImport.update({
    id: "/floatingips/",
    path: "/floatingips/",
    getParentRoute: () => AuthProjectsProjectIdNetworkRoute,
  } as any)
const AuthProjectsProjectIdComputeImagesIndexRoute =
  AuthProjectsProjectIdComputeImagesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthProjectsProjectIdComputeImagesRoute,
  } as any)
const AuthProjectsProjectIdComputeFlavorsIndexRoute =
  AuthProjectsProjectIdComputeFlavorsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthProjectsProjectIdComputeFlavorsRoute,
  } as any)
const AuthProjectsProjectIdComputeImagesImageIdRoute =
  AuthProjectsProjectIdComputeImagesImageIdRouteImport.update({
    id: "/$imageId",
    path: "/$imageId",
    getParentRoute: () => AuthProjectsProjectIdComputeImagesRoute,
  } as any)
const AuthProjectsProjectIdComputeFlavorsFlavorIdRoute =
  AuthProjectsProjectIdComputeFlavorsFlavorIdRouteImport.update({
    id: "/$flavorId",
    path: "/$flavorId",
    getParentRoute: () => AuthProjectsProjectIdComputeFlavorsRoute,
  } as any)
const AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute =
  AuthProjectsProjectIdStorageProviderStorageTypeIndexRouteImport.update({
    id: "/storage/$provider/$storageType/",
    path: "/storage/$provider/$storageType/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdServicesPcaPcaIdIndexRoute =
  AuthProjectsProjectIdServicesPcaPcaIdIndexRouteImport.update({
    id: "/services/pca/$pcaId/",
    path: "/services/pca/$pcaId/",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute =
  AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRouteImport.update(
    {
      id: "/securitygroups/$securityGroupId/",
      path: "/securitygroups/$securityGroupId/",
      getParentRoute: () => AuthProjectsProjectIdNetworkRoute,
    } as any,
  )
const AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute =
  AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRouteImport.update({
    id: "/floatingips/$floatingIpId/",
    path: "/floatingips/$floatingIpId/",
    getParentRoute: () => AuthProjectsProjectIdNetworkRoute,
  } as any)
const AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute =
  AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRouteImport.update({
    id: "/services/pca/$pcaId/$certificateId",
    path: "/services/pca/$pcaId/$certificateId",
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute =
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRouteImport.update(
    {
      id: "/storage/$provider/$storageType/$containerName/versions",
      path: "/storage/$provider/$storageType/$containerName/versions",
      getParentRoute: () => AuthProjectsProjectIdRoute,
    } as any,
  )
const AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute =
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRouteImport.update(
    {
      id: "/storage/$provider/$storageType/$containerName/objects/",
      path: "/storage/$provider/$storageType/$containerName/objects/",
      getParentRoute: () => AuthProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/aurora": typeof AuthAuroraRoute
  "/projects/$projectId": typeof AuthProjectsProjectIdRouteWithChildren
  "/accounts/": typeof AuthAccountsIndexRoute
  "/projects/": typeof AuthProjectsIndexRoute
  "/projects/$projectId/network": typeof AuthProjectsProjectIdNetworkRouteWithChildren
  "/projects/$projectId/": typeof AuthProjectsProjectIdIndexRoute
  "/projects/$projectId/compute/flavors": typeof AuthProjectsProjectIdComputeFlavorsRouteWithChildren
  "/projects/$projectId/compute/images": typeof AuthProjectsProjectIdComputeImagesRouteWithChildren
  "/projects/$projectId/compute/": typeof AuthProjectsProjectIdComputeIndexRoute
  "/projects/$projectId/network/": typeof AuthProjectsProjectIdNetworkIndexRoute
  "/projects/$projectId/services/": typeof AuthProjectsProjectIdServicesIndexRoute
  "/projects/$projectId/storage/": typeof AuthProjectsProjectIdStorageIndexRoute
  "/projects/$projectId/compute/flavors/$flavorId": typeof AuthProjectsProjectIdComputeFlavorsFlavorIdRoute
  "/projects/$projectId/compute/images/$imageId": typeof AuthProjectsProjectIdComputeImagesImageIdRoute
  "/projects/$projectId/compute/flavors/": typeof AuthProjectsProjectIdComputeFlavorsIndexRoute
  "/projects/$projectId/compute/images/": typeof AuthProjectsProjectIdComputeImagesIndexRoute
  "/projects/$projectId/network/floatingips/": typeof AuthProjectsProjectIdNetworkFloatingipsIndexRoute
  "/projects/$projectId/network/securitygroups/": typeof AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute
  "/projects/$projectId/services/pca/": typeof AuthProjectsProjectIdServicesPcaIndexRoute
  "/projects/$projectId/services/pca/$pcaId/$certificateId": typeof AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute
  "/projects/$projectId/network/floatingips/$floatingIpId/": typeof AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute
  "/projects/$projectId/network/securitygroups/$securityGroupId/": typeof AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute
  "/projects/$projectId/services/pca/$pcaId/": typeof AuthProjectsProjectIdServicesPcaPcaIdIndexRoute
  "/projects/$projectId/storage/$provider/$storageType/": typeof AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute
  "/projects/$projectId/storage/$provider/$storageType/$containerName/versions": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute
  "/projects/$projectId/storage/$provider/$storageType/$containerName/objects/": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/aurora": typeof AuthAuroraRoute
  "/accounts": typeof AuthAccountsIndexRoute
  "/projects": typeof AuthProjectsIndexRoute
  "/projects/$projectId": typeof AuthProjectsProjectIdIndexRoute
  "/projects/$projectId/compute": typeof AuthProjectsProjectIdComputeIndexRoute
  "/projects/$projectId/network": typeof AuthProjectsProjectIdNetworkIndexRoute
  "/projects/$projectId/services": typeof AuthProjectsProjectIdServicesIndexRoute
  "/projects/$projectId/storage": typeof AuthProjectsProjectIdStorageIndexRoute
  "/projects/$projectId/compute/flavors/$flavorId": typeof AuthProjectsProjectIdComputeFlavorsFlavorIdRoute
  "/projects/$projectId/compute/images/$imageId": typeof AuthProjectsProjectIdComputeImagesImageIdRoute
  "/projects/$projectId/compute/flavors": typeof AuthProjectsProjectIdComputeFlavorsIndexRoute
  "/projects/$projectId/compute/images": typeof AuthProjectsProjectIdComputeImagesIndexRoute
  "/projects/$projectId/network/floatingips": typeof AuthProjectsProjectIdNetworkFloatingipsIndexRoute
  "/projects/$projectId/network/securitygroups": typeof AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute
  "/projects/$projectId/services/pca": typeof AuthProjectsProjectIdServicesPcaIndexRoute
  "/projects/$projectId/services/pca/$pcaId/$certificateId": typeof AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute
  "/projects/$projectId/network/floatingips/$floatingIpId": typeof AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute
  "/projects/$projectId/network/securitygroups/$securityGroupId": typeof AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute
  "/projects/$projectId/services/pca/$pcaId": typeof AuthProjectsProjectIdServicesPcaPcaIdIndexRoute
  "/projects/$projectId/storage/$provider/$storageType": typeof AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute
  "/projects/$projectId/storage/$provider/$storageType/$containerName/versions": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute
  "/projects/$projectId/storage/$provider/$storageType/$containerName/objects": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/about": typeof AboutRoute
  "/_auth/aurora": typeof AuthAuroraRoute
  "/_auth/projects/$projectId": typeof AuthProjectsProjectIdRouteWithChildren
  "/_auth/accounts/": typeof AuthAccountsIndexRoute
  "/_auth/projects/": typeof AuthProjectsIndexRoute
  "/_auth/projects/$projectId/network": typeof AuthProjectsProjectIdNetworkRouteWithChildren
  "/_auth/projects/$projectId/": typeof AuthProjectsProjectIdIndexRoute
  "/_auth/projects/$projectId/compute/flavors": typeof AuthProjectsProjectIdComputeFlavorsRouteWithChildren
  "/_auth/projects/$projectId/compute/images": typeof AuthProjectsProjectIdComputeImagesRouteWithChildren
  "/_auth/projects/$projectId/compute/": typeof AuthProjectsProjectIdComputeIndexRoute
  "/_auth/projects/$projectId/network/": typeof AuthProjectsProjectIdNetworkIndexRoute
  "/_auth/projects/$projectId/services/": typeof AuthProjectsProjectIdServicesIndexRoute
  "/_auth/projects/$projectId/storage/": typeof AuthProjectsProjectIdStorageIndexRoute
  "/_auth/projects/$projectId/compute/flavors/$flavorId": typeof AuthProjectsProjectIdComputeFlavorsFlavorIdRoute
  "/_auth/projects/$projectId/compute/images/$imageId": typeof AuthProjectsProjectIdComputeImagesImageIdRoute
  "/_auth/projects/$projectId/compute/flavors/": typeof AuthProjectsProjectIdComputeFlavorsIndexRoute
  "/_auth/projects/$projectId/compute/images/": typeof AuthProjectsProjectIdComputeImagesIndexRoute
  "/_auth/projects/$projectId/network/floatingips/": typeof AuthProjectsProjectIdNetworkFloatingipsIndexRoute
  "/_auth/projects/$projectId/network/securitygroups/": typeof AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute
  "/_auth/projects/$projectId/services/pca/": typeof AuthProjectsProjectIdServicesPcaIndexRoute
  "/_auth/projects/$projectId/services/pca/$pcaId/$certificateId": typeof AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute
  "/_auth/projects/$projectId/network/floatingips/$floatingIpId/": typeof AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute
  "/_auth/projects/$projectId/network/securitygroups/$securityGroupId/": typeof AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute
  "/_auth/projects/$projectId/services/pca/$pcaId/": typeof AuthProjectsProjectIdServicesPcaPcaIdIndexRoute
  "/_auth/projects/$projectId/storage/$provider/$storageType/": typeof AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute
  "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/versions": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute
  "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/objects/": typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/aurora"
    | "/projects/$projectId"
    | "/accounts/"
    | "/projects/"
    | "/projects/$projectId/network"
    | "/projects/$projectId/"
    | "/projects/$projectId/compute/flavors"
    | "/projects/$projectId/compute/images"
    | "/projects/$projectId/compute/"
    | "/projects/$projectId/network/"
    | "/projects/$projectId/services/"
    | "/projects/$projectId/storage/"
    | "/projects/$projectId/compute/flavors/$flavorId"
    | "/projects/$projectId/compute/images/$imageId"
    | "/projects/$projectId/compute/flavors/"
    | "/projects/$projectId/compute/images/"
    | "/projects/$projectId/network/floatingips/"
    | "/projects/$projectId/network/securitygroups/"
    | "/projects/$projectId/services/pca/"
    | "/projects/$projectId/services/pca/$pcaId/$certificateId"
    | "/projects/$projectId/network/floatingips/$floatingIpId/"
    | "/projects/$projectId/network/securitygroups/$securityGroupId/"
    | "/projects/$projectId/services/pca/$pcaId/"
    | "/projects/$projectId/storage/$provider/$storageType/"
    | "/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
    | "/projects/$projectId/storage/$provider/$storageType/$containerName/objects/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/aurora"
    | "/accounts"
    | "/projects"
    | "/projects/$projectId"
    | "/projects/$projectId/compute"
    | "/projects/$projectId/network"
    | "/projects/$projectId/services"
    | "/projects/$projectId/storage"
    | "/projects/$projectId/compute/flavors/$flavorId"
    | "/projects/$projectId/compute/images/$imageId"
    | "/projects/$projectId/compute/flavors"
    | "/projects/$projectId/compute/images"
    | "/projects/$projectId/network/floatingips"
    | "/projects/$projectId/network/securitygroups"
    | "/projects/$projectId/services/pca"
    | "/projects/$projectId/services/pca/$pcaId/$certificateId"
    | "/projects/$projectId/network/floatingips/$floatingIpId"
    | "/projects/$projectId/network/securitygroups/$securityGroupId"
    | "/projects/$projectId/services/pca/$pcaId"
    | "/projects/$projectId/storage/$provider/$storageType"
    | "/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
    | "/projects/$projectId/storage/$provider/$storageType/$containerName/objects"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/about"
    | "/_auth/aurora"
    | "/_auth/projects/$projectId"
    | "/_auth/accounts/"
    | "/_auth/projects/"
    | "/_auth/projects/$projectId/network"
    | "/_auth/projects/$projectId/"
    | "/_auth/projects/$projectId/compute/flavors"
    | "/_auth/projects/$projectId/compute/images"
    | "/_auth/projects/$projectId/compute/"
    | "/_auth/projects/$projectId/network/"
    | "/_auth/projects/$projectId/services/"
    | "/_auth/projects/$projectId/storage/"
    | "/_auth/projects/$projectId/compute/flavors/$flavorId"
    | "/_auth/projects/$projectId/compute/images/$imageId"
    | "/_auth/projects/$projectId/compute/flavors/"
    | "/_auth/projects/$projectId/compute/images/"
    | "/_auth/projects/$projectId/network/floatingips/"
    | "/_auth/projects/$projectId/network/securitygroups/"
    | "/_auth/projects/$projectId/services/pca/"
    | "/_auth/projects/$projectId/services/pca/$pcaId/$certificateId"
    | "/_auth/projects/$projectId/network/floatingips/$floatingIpId/"
    | "/_auth/projects/$projectId/network/securitygroups/$securityGroupId/"
    | "/_auth/projects/$projectId/services/pca/$pcaId/"
    | "/_auth/projects/$projectId/storage/$provider/$storageType/"
    | "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
    | "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/objects/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/aurora": {
      id: "/_auth/aurora"
      path: "/aurora"
      fullPath: "/aurora"
      preLoaderRoute: typeof AuthAuroraRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/projects/": {
      id: "/_auth/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/accounts/": {
      id: "/_auth/accounts/"
      path: "/accounts"
      fullPath: "/accounts/"
      preLoaderRoute: typeof AuthAccountsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/projects/$projectId": {
      id: "/_auth/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/projects/$projectId/": {
      id: "/_auth/projects/$projectId/"
      path: "/"
      fullPath: "/projects/$projectId/"
      preLoaderRoute: typeof AuthProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/network": {
      id: "/_auth/projects/$projectId/network"
      path: "/network"
      fullPath: "/projects/$projectId/network"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/storage/": {
      id: "/_auth/projects/$projectId/storage/"
      path: "/storage"
      fullPath: "/projects/$projectId/storage/"
      preLoaderRoute: typeof AuthProjectsProjectIdStorageIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/services/": {
      id: "/_auth/projects/$projectId/services/"
      path: "/services"
      fullPath: "/projects/$projectId/services/"
      preLoaderRoute: typeof AuthProjectsProjectIdServicesIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/network/": {
      id: "/_auth/projects/$projectId/network/"
      path: "/"
      fullPath: "/projects/$projectId/network/"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdNetworkRoute
    }
    "/_auth/projects/$projectId/compute/": {
      id: "/_auth/projects/$projectId/compute/"
      path: "/compute"
      fullPath: "/projects/$projectId/compute/"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/compute/images": {
      id: "/_auth/projects/$projectId/compute/images"
      path: "/compute/images"
      fullPath: "/projects/$projectId/compute/images"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeImagesRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/compute/flavors": {
      id: "/_auth/projects/$projectId/compute/flavors"
      path: "/compute/flavors"
      fullPath: "/projects/$projectId/compute/flavors"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeFlavorsRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/services/pca/": {
      id: "/_auth/projects/$projectId/services/pca/"
      path: "/services/pca"
      fullPath: "/projects/$projectId/services/pca/"
      preLoaderRoute: typeof AuthProjectsProjectIdServicesPcaIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/network/securitygroups/": {
      id: "/_auth/projects/$projectId/network/securitygroups/"
      path: "/securitygroups"
      fullPath: "/projects/$projectId/network/securitygroups/"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkSecuritygroupsIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdNetworkRoute
    }
    "/_auth/projects/$projectId/network/floatingips/": {
      id: "/_auth/projects/$projectId/network/floatingips/"
      path: "/floatingips"
      fullPath: "/projects/$projectId/network/floatingips/"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkFloatingipsIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdNetworkRoute
    }
    "/_auth/projects/$projectId/compute/images/": {
      id: "/_auth/projects/$projectId/compute/images/"
      path: "/"
      fullPath: "/projects/$projectId/compute/images/"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeImagesIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdComputeImagesRoute
    }
    "/_auth/projects/$projectId/compute/flavors/": {
      id: "/_auth/projects/$projectId/compute/flavors/"
      path: "/"
      fullPath: "/projects/$projectId/compute/flavors/"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeFlavorsIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdComputeFlavorsRoute
    }
    "/_auth/projects/$projectId/compute/images/$imageId": {
      id: "/_auth/projects/$projectId/compute/images/$imageId"
      path: "/$imageId"
      fullPath: "/projects/$projectId/compute/images/$imageId"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeImagesImageIdRouteImport
      parentRoute: typeof AuthProjectsProjectIdComputeImagesRoute
    }
    "/_auth/projects/$projectId/compute/flavors/$flavorId": {
      id: "/_auth/projects/$projectId/compute/flavors/$flavorId"
      path: "/$flavorId"
      fullPath: "/projects/$projectId/compute/flavors/$flavorId"
      preLoaderRoute: typeof AuthProjectsProjectIdComputeFlavorsFlavorIdRouteImport
      parentRoute: typeof AuthProjectsProjectIdComputeFlavorsRoute
    }
    "/_auth/projects/$projectId/storage/$provider/$storageType/": {
      id: "/_auth/projects/$projectId/storage/$provider/$storageType/"
      path: "/storage/$provider/$storageType"
      fullPath: "/projects/$projectId/storage/$provider/$storageType/"
      preLoaderRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/services/pca/$pcaId/": {
      id: "/_auth/projects/$projectId/services/pca/$pcaId/"
      path: "/services/pca/$pcaId"
      fullPath: "/projects/$projectId/services/pca/$pcaId/"
      preLoaderRoute: typeof AuthProjectsProjectIdServicesPcaPcaIdIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/network/securitygroups/$securityGroupId/": {
      id: "/_auth/projects/$projectId/network/securitygroups/$securityGroupId/"
      path: "/securitygroups/$securityGroupId"
      fullPath: "/projects/$projectId/network/securitygroups/$securityGroupId/"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdNetworkRoute
    }
    "/_auth/projects/$projectId/network/floatingips/$floatingIpId/": {
      id: "/_auth/projects/$projectId/network/floatingips/$floatingIpId/"
      path: "/floatingips/$floatingIpId"
      fullPath: "/projects/$projectId/network/floatingips/$floatingIpId/"
      preLoaderRoute: typeof AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdNetworkRoute
    }
    "/_auth/projects/$projectId/services/pca/$pcaId/$certificateId": {
      id: "/_auth/projects/$projectId/services/pca/$pcaId/$certificateId"
      path: "/services/pca/$pcaId/$certificateId"
      fullPath: "/projects/$projectId/services/pca/$pcaId/$certificateId"
      preLoaderRoute: typeof AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/versions": {
      id: "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
      path: "/storage/$provider/$storageType/$containerName/versions"
      fullPath: "/projects/$projectId/storage/$provider/$storageType/$containerName/versions"
      preLoaderRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/objects/": {
      id: "/_auth/projects/$projectId/storage/$provider/$storageType/$containerName/objects/"
      path: "/storage/$provider/$storageType/$containerName/objects"
      fullPath: "/projects/$projectId/storage/$provider/$storageType/$containerName/objects/"
      preLoaderRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
  }
}

interface AuthProjectsProjectIdNetworkRouteChildren {
  AuthProjectsProjectIdNetworkIndexRoute: typeof AuthProjectsProjectIdNetworkIndexRoute
  AuthProjectsProjectIdNetworkFloatingipsIndexRoute: typeof AuthProjectsProjectIdNetworkFloatingipsIndexRoute
  AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute: typeof AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute
  AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute: typeof AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute
  AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute: typeof AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute
}

const AuthProjectsProjectIdNetworkRouteChildren: AuthProjectsProjectIdNetworkRouteChildren =
  {
    AuthProjectsProjectIdNetworkIndexRoute:
      AuthProjectsProjectIdNetworkIndexRoute,
    AuthProjectsProjectIdNetworkFloatingipsIndexRoute:
      AuthProjectsProjectIdNetworkFloatingipsIndexRoute,
    AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute:
      AuthProjectsProjectIdNetworkSecuritygroupsIndexRoute,
    AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute:
      AuthProjectsProjectIdNetworkFloatingipsFloatingIpIdIndexRoute,
    AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute:
      AuthProjectsProjectIdNetworkSecuritygroupsSecurityGroupIdIndexRoute,
  }

const AuthProjectsProjectIdNetworkRouteWithChildren =
  AuthProjectsProjectIdNetworkRoute._addFileChildren(
    AuthProjectsProjectIdNetworkRouteChildren,
  )

interface AuthProjectsProjectIdComputeFlavorsRouteChildren {
  AuthProjectsProjectIdComputeFlavorsFlavorIdRoute: typeof AuthProjectsProjectIdComputeFlavorsFlavorIdRoute
  AuthProjectsProjectIdComputeFlavorsIndexRoute: typeof AuthProjectsProjectIdComputeFlavorsIndexRoute
}

const AuthProjectsProjectIdComputeFlavorsRouteChildren: AuthProjectsProjectIdComputeFlavorsRouteChildren =
  {
    AuthProjectsProjectIdComputeFlavorsFlavorIdRoute:
      AuthProjectsProjectIdComputeFlavorsFlavorIdRoute,
    AuthProjectsProjectIdComputeFlavorsIndexRoute:
      AuthProjectsProjectIdComputeFlavorsIndexRoute,
  }

const AuthProjectsProjectIdComputeFlavorsRouteWithChildren =
  AuthProjectsProjectIdComputeFlavorsRoute._addFileChildren(
    AuthProjectsProjectIdComputeFlavorsRouteChildren,
  )

interface AuthProjectsProjectIdComputeImagesRouteChildren {
  AuthProjectsProjectIdComputeImagesImageIdRoute: typeof AuthProjectsProjectIdComputeImagesImageIdRoute
  AuthProjectsProjectIdComputeImagesIndexRoute: typeof AuthProjectsProjectIdComputeImagesIndexRoute
}

const AuthProjectsProjectIdComputeImagesRouteChildren: AuthProjectsProjectIdComputeImagesRouteChildren =
  {
    AuthProjectsProjectIdComputeImagesImageIdRoute:
      AuthProjectsProjectIdComputeImagesImageIdRoute,
    AuthProjectsProjectIdComputeImagesIndexRoute:
      AuthProjectsProjectIdComputeImagesIndexRoute,
  }

const AuthProjectsProjectIdComputeImagesRouteWithChildren =
  AuthProjectsProjectIdComputeImagesRoute._addFileChildren(
    AuthProjectsProjectIdComputeImagesRouteChildren,
  )

interface AuthProjectsProjectIdRouteChildren {
  AuthProjectsProjectIdNetworkRoute: typeof AuthProjectsProjectIdNetworkRouteWithChildren
  AuthProjectsProjectIdIndexRoute: typeof AuthProjectsProjectIdIndexRoute
  AuthProjectsProjectIdComputeFlavorsRoute: typeof AuthProjectsProjectIdComputeFlavorsRouteWithChildren
  AuthProjectsProjectIdComputeImagesRoute: typeof AuthProjectsProjectIdComputeImagesRouteWithChildren
  AuthProjectsProjectIdComputeIndexRoute: typeof AuthProjectsProjectIdComputeIndexRoute
  AuthProjectsProjectIdServicesIndexRoute: typeof AuthProjectsProjectIdServicesIndexRoute
  AuthProjectsProjectIdStorageIndexRoute: typeof AuthProjectsProjectIdStorageIndexRoute
  AuthProjectsProjectIdServicesPcaIndexRoute: typeof AuthProjectsProjectIdServicesPcaIndexRoute
  AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute: typeof AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute
  AuthProjectsProjectIdServicesPcaPcaIdIndexRoute: typeof AuthProjectsProjectIdServicesPcaPcaIdIndexRoute
  AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute: typeof AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute
}

const AuthProjectsProjectIdRouteChildren: AuthProjectsProjectIdRouteChildren = {
  AuthProjectsProjectIdNetworkRoute:
    AuthProjectsProjectIdNetworkRouteWithChildren,
  AuthProjectsProjectIdIndexRoute: AuthProjectsProjectIdIndexRoute,
  AuthProjectsProjectIdComputeFlavorsRoute:
    AuthProjectsProjectIdComputeFlavorsRouteWithChildren,
  AuthProjectsProjectIdComputeImagesRoute:
    AuthProjectsProjectIdComputeImagesRouteWithChildren,
  AuthProjectsProjectIdComputeIndexRoute:
    AuthProjectsProjectIdComputeIndexRoute,
  AuthProjectsProjectIdServicesIndexRoute:
    AuthProjectsProjectIdServicesIndexRoute,
  AuthProjectsProjectIdStorageIndexRoute:
    AuthProjectsProjectIdStorageIndexRoute,
  AuthProjectsProjectIdServicesPcaIndexRoute:
    AuthProjectsProjectIdServicesPcaIndexRoute,
  AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute:
    AuthProjectsProjectIdServicesPcaPcaIdCertificateIdRoute,
  AuthProjectsProjectIdServicesPcaPcaIdIndexRoute:
    AuthProjectsProjectIdServicesPcaPcaIdIndexRoute,
  AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute:
    AuthProjectsProjectIdStorageProviderStorageTypeIndexRoute,
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute:
    AuthProjectsProjectIdStorageProviderStorageTypeContainerNameVersionsRoute,
  AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute:
    AuthProjectsProjectIdStorageProviderStorageTypeContainerNameObjectsIndexRoute,
}

const AuthProjectsProjectIdRouteWithChildren =
  AuthProjectsProjectIdRoute._addFileChildren(
    AuthProjectsProjectIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthAuroraRoute: typeof AuthAuroraRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRouteWithChildren
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuroraRoute: AuthAuroraRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRouteWithChildren,
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
