packages:
  - "apps/*"
  - "!apps/dev"
  - "packages/*"

allowBuilds:
  "@swc/core": true
  esbuild: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - tmp
  - "@cloudoperators/juno-ui-components"
  - "@fastify/static@10.1.2"

overrides:
  "@fastify/static@<10.1.2": ^10.1.2
  "tmp@<0.2.6": ">=0.2.6"
  "js-yaml@>=3.0.0 <3.15.2": "3.15.2"
  "js-yaml@>=4.0.0 <4.3.2": "4.3.2"
  "esbuild@>=0.27.3 <0.28.1": ">=0.28.1"
