packages:
  - "apps/*"
  - "!apps/dev"
  - "packages/*"

allowBuilds:
  "@swc/core": true
  esbuild: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - tmp
  - "@cloudoperators/juno-ui-components"
  - "@fastify/static@10.1.2"

overrides:
  "@fastify/static@<10.1.2": ^10.1.2
  "tmp@<0.2.6": ">=0.2.6"
