export const ERROR_CODES = {
  FLAVORS_UNAUTHORIZED: "FLAVORS_UNAUTHORIZED",
  FLAVORS_FORBIDDEN: "FLAVORS_FORBIDDEN",
  FLAVORS_NOT_FOUND: "FLAVORS_NOT_FOUND",
  FLAVORS_SERVER_ERROR: "FLAVORS_SERVER_ERROR",
  FLAVORS_FETCH_FAILED: "FLAVORS_FETCH_FAILED",
  FLAVORS_PARSE_ERROR: "FLAVORS_PARSE_ERROR",
} as const
