export const ERROR_CODES = {
  // Flavors
  FLAVORS_UNAUTHORIZED: "FLAVORS_UNAUTHORIZED",
  FLAVORS_FORBIDDEN: "FLAVORS_FORBIDDEN",
  FLAVORS_NOT_FOUND: "FLAVORS_NOT_FOUND",
  FLAVORS_SERVER_ERROR: "FLAVORS_SERVER_ERROR",
  FLAVORS_FETCH_FAILED: "FLAVORS_FETCH_FAILED",
  FLAVORS_PARSE_ERROR: "FLAVORS_PARSE_ERROR",

  // Create Flavor
  CREATE_FLAVOR_INVALID_DATA: "CREATE_FLAVOR_INVALID_DATA",
  CREATE_FLAVOR_UNAUTHORIZED: "CREATE_FLAVOR_UNAUTHORIZED",
  CREATE_FLAVOR_FORBIDDEN: "CREATE_FLAVOR_FORBIDDEN",
  CREATE_FLAVOR_CONFLICT: "CREATE_FLAVOR_CONFLICT",
  CREATE_FLAVOR_SERVER_ERROR: "CREATE_FLAVOR_SERVER_ERROR",
  CREATE_FLAVOR_FAILED: "CREATE_FLAVOR_FAILED",

  // Delete Flavor
  DELETE_FLAVOR_FAILED: "DELETE_FLAVOR_FAILED",
  DELETE_FLAVOR_UNAUTHORIZED: "DELETE_FLAVOR_UNAUTHORIZED",
  DELETE_FLAVOR_FORBIDDEN: "DELETE_FLAVOR_FORBIDDEN",
  DELETE_FLAVOR_NOT_FOUND: "DELETE_FLAVOR_NOT_FOUND",
  DELETE_FLAVOR_SERVER_ERROR: "DELETE_FLAVOR_SERVER_ERROR",
  DELETE_FLAVOR_INVALID_ID: "DELETE_FLAVOR_INVALID_ID",

  // Create Extra Specs
  CREATE_EXTRA_SPECS_FAILED: "CREATE_EXTRA_SPECS_FAILED",
  CREATE_EXTRA_SPECS_UNAUTHORIZED: "CREATE_EXTRA_SPECS_UNAUTHORIZED",
  CREATE_EXTRA_SPECS_FORBIDDEN: "CREATE_EXTRA_SPECS_FORBIDDEN",
  CREATE_EXTRA_SPECS_NOT_FOUND: "CREATE_EXTRA_SPECS_NOT_FOUND",
  CREATE_EXTRA_SPECS_CONFLICT: "CREATE_EXTRA_SPECS_CONFLICT",
  CREATE_EXTRA_SPECS_INVALID_DATA: "CREATE_EXTRA_SPECS_INVALID_DATA",
  CREATE_EXTRA_SPECS_PARSE_ERROR: "CREATE_EXTRA_SPECS_PARSE_ERROR",
  CREATE_EXTRA_SPECS_SERVER_ERROR: "CREATE_EXTRA_SPECS_SERVER_ERROR",

  // Get Extra Specs
  GET_EXTRA_SPECS_FAILED: "GET_EXTRA_SPECS_FAILED",
  GET_EXTRA_SPECS_UNAUTHORIZED: "GET_EXTRA_SPECS_UNAUTHORIZED",
  GET_EXTRA_SPECS_FORBIDDEN: "GET_EXTRA_SPECS_FORBIDDEN",
  GET_EXTRA_SPECS_NOT_FOUND: "GET_EXTRA_SPECS_NOT_FOUND",
  GET_EXTRA_SPECS_SERVER_ERROR: "GET_EXTRA_SPECS_SERVER_ERROR",
  GET_EXTRA_SPECS_PARSE_ERROR: "GET_EXTRA_SPECS_PARSE_ERROR",

  // Delete Extra Spec
  DELETE_EXTRA_SPEC_FAILED: "DELETE_EXTRA_SPEC_FAILED",
  DELETE_EXTRA_SPEC_UNAUTHORIZED: "DELETE_EXTRA_SPEC_UNAUTHORIZED",
  DELETE_EXTRA_SPEC_FORBIDDEN: "DELETE_EXTRA_SPEC_FORBIDDEN",
  DELETE_EXTRA_SPEC_NOT_FOUND: "DELETE_EXTRA_SPEC_NOT_FOUND",
  DELETE_EXTRA_SPEC_SERVER_ERROR: "DELETE_EXTRA_SPEC_SERVER_ERROR",
  DELETE_EXTRA_SPEC_INVALID_KEY: "DELETE_EXTRA_SPEC_INVALID_KEY",

  // Get Access flavor projects
  GET_FLAVOR_ACCESS_UNAUTHORIZED: "GET_FLAVOR_ACCESS_UNAUTHORIZED",
  GET_FLAVOR_ACCESS_FORBIDDEN: "GET_FLAVOR_ACCESS_FORBIDDEN",
  GET_FLAVOR_ACCESS_NOT_FOUND: "GET_FLAVOR_ACCESS_NOT_FOUND",
  GET_FLAVOR_ACCESS_SERVER_ERROR: "GET_FLAVOR_ACCESS_SERVER_ERROR",
  GET_FLAVOR_ACCESS_FAILED: "GET_FLAVOR_ACCESS_FAILED",

  // Add Tenant Access
  ADD_TENANT_ACCESS_FAILED: "ADD_TENANT_ACCESS_FAILED",
  ADD_TENANT_ACCESS_INVALID_DATA: "ADD_TENANT_ACCESS_INVALID_DATA",
  ADD_TENANT_ACCESS_UNAUTHORIZED: "ADD_TENANT_ACCESS_UNAUTHORIZED",
  ADD_TENANT_ACCESS_FORBIDDEN: "ADD_TENANT_ACCESS_FORBIDDEN",
  ADD_TENANT_ACCESS_NOT_FOUND: "ADD_TENANT_ACCESS_NOT_FOUND",
  ADD_TENANT_ACCESS_CONFLICT: "ADD_TENANT_ACCESS_CONFLICT",
  ADD_TENANT_ACCESS_SERVER_ERROR: "ADD_TENANT_ACCESS_SERVER_ERROR",

  // Remove Tenant Access
  REMOVE_TENANT_ACCESS_FAILED: "REMOVE_TENANT_ACCESS_FAILED",
  REMOVE_TENANT_ACCESS_INVALID_DATA: "REMOVE_TENANT_ACCESS_INVALID_DATA",
  REMOVE_TENANT_ACCESS_UNAUTHORIZED: "REMOVE_TENANT_ACCESS_UNAUTHORIZED",
  REMOVE_TENANT_ACCESS_FORBIDDEN: "REMOVE_TENANT_ACCESS_FORBIDDEN",
  REMOVE_TENANT_ACCESS_NOT_FOUND: "REMOVE_TENANT_ACCESS_NOT_FOUND",
  REMOVE_TENANT_ACCESS_CONFLICT: "REMOVE_TENANT_ACCESS_CONFLICT",
  REMOVE_TENANT_ACCESS_SERVER_ERROR: "REMOVE_TENANT_ACCESS_SERVER_ERROR",

  // Service Connection Errors
  COMPUTE_SERVICE_UNAVAILABLE: "COMPUTE_SERVICE_UNAVAILABLE",
  COMPUTE_SERVICE_CONNECTION_FAILED: "COMPUTE_SERVICE_CONNECTION_FAILED",
} as const
