export const HTTP_STATUS_CODE_TO_NAME = {
  400: "BAD_REQUEST",
  401: "UNAUTHORIZED",
  403: "FORBIDDEN",
  404: "NOT_FOUND",
  409: "CONFLICT",
  412: "PRECONDITION_FAILED",
} as const

export const DEFAULT_ERROR_NAME = "INTERNAL_SERVER_ERROR"
