export interface RulePreset {
  value: string
  label: string
  protocol: string | null
  portRangeMin: number | null
  portRangeMax: number | null
  description: string
}

export const RULE_PRESETS: RulePreset[] = [
  // Custom rules (appears first)
  {
    value: "custom-tcp",
    label: "Custom TCP Rule",
    protocol: "tcp",
    portRangeMin: null,
    portRangeMax: null,
    description: "Custom TCP rule",
  },
  {
    value: "custom-udp",
    label: "Custom UDP Rule",
    protocol: "udp",
    portRangeMin: null,
    portRangeMax: null,
    description: "Custom UDP rule",
  },
  {
    value: "custom-icmp",
    label: "Custom ICMP Rule",
    protocol: "icmp",
    portRangeMin: null,
    portRangeMax: null,
    description: "Custom ICMP rule",
  },
  {
    value: "all-tcp",
    label: "All TCP",
    protocol: "tcp",
    portRangeMin: 1,
    portRangeMax: 65535,
    description: "All TCP ports",
  },
  {
    value: "all-udp",
    label: "All UDP",
    protocol: "udp",
    portRangeMin: 1,
    portRangeMax: 65535,
    description: "All UDP ports",
  },
  {
    value: "all-icmp",
    label: "All ICMP",
    protocol: "icmp",
    portRangeMin: null,
    portRangeMax: null,
    description: "All ICMP traffic",
  },
  {
    value: "other-protocol",
    label: "Other Protocol",
    protocol: null,
    portRangeMin: null,
    portRangeMax: null,
    description: "Custom protocol number",
  },

  // Common protocols
  {
    value: "dns-tcp",
    label: "DNS (TCP)",
    protocol: "tcp",
    portRangeMin: 53,
    portRangeMax: 53,
    description: "Domain Name System",
  },
  {
    value: "dns-udp",
    label: "DNS (UDP)",
    protocol: "udp",
    portRangeMin: 53,
    portRangeMax: 53,
    description: "Domain Name System",
  },
  {
    value: "http",
    label: "HTTP",
    protocol: "tcp",
    portRangeMin: 80,
    portRangeMax: 80,
    description: "Web traffic",
  },
  {
    value: "https",
    label: "HTTPS",
    protocol: "tcp",
    portRangeMin: 443,
    portRangeMax: 443,
    description: "Secure web traffic",
  },
  {
    value: "imap",
    label: "IMAP",
    protocol: "tcp",
    portRangeMin: 143,
    portRangeMax: 143,
    description: "Email retrieval",
  },
  {
    value: "imaps",
    label: "IMAPS",
    protocol: "tcp",
    portRangeMin: 993,
    portRangeMax: 993,
    description: "Secure IMAP",
  },
  {
    value: "ldap",
    label: "LDAP",
    protocol: "tcp",
    portRangeMin: 389,
    portRangeMax: 389,
    description: "Directory services",
  },
  {
    value: "ms-sql",
    label: "MS SQL",
    protocol: "tcp",
    portRangeMin: 1433,
    portRangeMax: 1433,
    description: "Microsoft SQL Server",
  },
  {
    value: "mysql",
    label: "MySQL",
    protocol: "tcp",
    portRangeMin: 3306,
    portRangeMax: 3306,
    description: "MySQL database",
  },
  {
    value: "ntp",
    label: "NTP",
    protocol: "udp",
    portRangeMin: 123,
    portRangeMax: 123,
    description: "Network Time Protocol",
  },
  {
    value: "pop3",
    label: "POP3",
    protocol: "tcp",
    portRangeMin: 110,
    portRangeMax: 110,
    description: "Email retrieval",
  },
  {
    value: "pop3s",
    label: "POP3S",
    protocol: "tcp",
    portRangeMin: 995,
    portRangeMax: 995,
    description: "Secure POP3",
  },
  {
    value: "rdp",
    label: "RDP",
    protocol: "tcp",
    portRangeMin: 3389,
    portRangeMax: 3389,
    description: "Remote Desktop",
  },
  {
    value: "ssh",
    label: "SSH",
    protocol: "tcp",
    portRangeMin: 22,
    portRangeMax: 22,
    description: "Secure Shell",
  },
  {
    value: "smtp",
    label: "SMTP",
    protocol: "tcp",
    portRangeMin: 25,
    portRangeMax: 25,
    description: "Email sending",
  },
  {
    value: "smtps",
    label: "SMTPS",
    protocol: "tcp",
    portRangeMin: 465,
    portRangeMax: 465,
    description: "Secure SMTP",
  },
]
